task 0

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
-# a Bash script that transfers a file from our client to a server
+# A Bash script that transfers a file from our client to a server
 
 if [ $# -lt 4 ]; then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit 1
+        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+        exit 1
 fi
 
 path_2_file=$1
@@ -11,4 +11,14 @@ server_ip=$2
 username=$3
 ssh_key=$4
 
-scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_2_file" "$username"@"$server_ip":~/
+echo "Transferring file from $path_2_file to $username@$server_ip..."
+
+# Adding -v for debugging SCP
+scp -v -o StrictHostKeyChecking=no -i "$ssh_key" "$path_2_file" "$username"@"$server_ip":~/
+
+if [ $? -eq 0 ]; then
+    echo "File transferred successfully!"
+else
+    echo "File transfer failed."
+fi
+
